### ISSUE TITLE
requests dependency

### ISSUE THREAD

**Issue by ezekriSCW** [criteo/hwbench#12]
`redfish` lib requires `requests`

**Comment by anisse** [comment]
This one can bee seen in the generated requirements file: https://github.com/criteo/hwbench/blob/fb1286726d8fc53ff295b5e533191bf8999ceda1/requirements/base.txt#L490 ; did you use it during install?

**Comment by ezekriSCW** [comment]
didn't checked `base.txt` before writing the issue, sorry
what led me to write this issue is the following message I've got during `setup.py install`
`error: The 'requests' distribution was not found and is required by redfish`
So I've installed `requests` manually and `setup.py install` again so that it goes through...

**Comment by anisse** [comment]
Yes, usually the recommended way si to use "pip install ." and it will use the setup.py and its declared dependencies, but also do recursive dependency installs.

**Comment by ezekriSCW** [comment]
Alright, So I close this issue as it's already handled
