### ISSUE TITLE
Python minimal supported version

### ISSUE THREAD

**Issue by ezekriSCW** [criteo/hwbench#6]
To document: hwbench requires Python 3.9 or higher
NB: tested with python3.8 --> doesn't work

**Comment by beorn-** [comment]
It is in the setup.py and the tox.ini. Do you mean to add information about it in the README.md file?

**Comment by ErwanAliasr1** [comment]
Added the info in https://github.com/criteo/hwbench/pull/14

**Comment by ErwanAliasr1** [comment]
I think we can close this issue, @ezekriSCW do you agree ?

**Comment by ezekriSCW** [comment]
Agree, I close it
thanks @ErwanAliasr1
