### ISSUE TITLE
Turbostat dependency

### ISSUE THREAD

**Issue by ezekriSCW** [criteo/hwbench#7]
requires recent version of `turbostat`
turbostat 2020.03.20 --> KO
turbostat 2024.05.10 --> OK
turbostat needs to be compiled as autonomous binary from [Linux Kernel power tools](https://github.com/torvalds/linux/tree/master/tools/power/x86/turbostat) 
Note that turbaostat requires libcap-dev

**Comment by Arno500** [comment]
Maybe @ErwanAliasr1 can enlighten us on this, but the tool need (it does not currently) to support more versions if possible, unless some required metrics are not provided.
I would expect hwbench to crash because of a different output format from turbostat

**Comment by ErwanAliasr1** [comment]
Yeah the parsing is changing pretty often.

I think that could be handled at the same time as issue #11 by having a version check at startup time.

**Comment by ErwanAliasr1** [comment]
Added a note in https://github.com/criteo/hwbench/pull/14

**Comment by ErwanAliasr1** [comment]
Solved in https://github.com/criteo/hwbench/pull/20
