### ISSUE TITLE
stress-ng dependency

### ISSUE THREAD

**Issue by ezekriSCW** [criteo/hwbench#8]
hwbench requires `stress-ng` [0.17.4](https://github.com/ColinIanKing/stress-ng/tarball/V0.17.04) or higher

**Comment by anisse** [comment]
This one is detected at runtime if you run a benchmark with a different `stress-ng` version; what would you expect instead? A message earlier in the run? Documenting the dependency? Supporting more `stress-ng` versions?

**Comment by ErwanAliasr1** [comment]
Added a note in #14

**Comment by ErwanAliasr1** [comment]
Solved in https://github.com/criteo/hwbench/pull/20
